/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'access-requests': AccessRequest;
    waitlist: Waitlist;
    orders: Order;
    reviews: Review;
    media: Media;
    categories: Category;
    products: Product;
    'founder-profiles': FounderProfile;
    'founder-keys': FounderKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'access-requests': AccessRequestsSelect<false> | AccessRequestsSelect<true>;
    waitlist: WaitlistSelect<false> | WaitlistSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'founder-profiles': FounderProfilesSelect<false> | FounderProfilesSelect<true>;
    'founder-keys': FounderKeysSelect<false> | FounderKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'batch-001-settings': Batch001Setting;
  };
  globalsSelect: {
    'batch-001-settings': Batch001SettingsSelect<false> | Batch001SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  phoneNumber?: string | null;
  role: 'admin' | 'customer';
  /**
   * Used later for Birthday Protocol automation.
   */
  birthDate?: string | null;
  isFounder?: boolean | null;
  /**
   * Founder position from 1 to 50. Example: 12 = 012/050.
   */
  founderNumber?: number | null;
  /**
   * Annual customer spending in PKR.
   */
  annualSpend?: number | null;
  referralCode?: string | null;
  originPoints?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-requests".
 */
export interface AccessRequest {
  id: number;
  name: string;
  email: string;
  phoneNumber?: string | null;
  /**
   * Customer date of birth collected at key request.
   */
  birthDate?: string | null;
  /**
   * Automatically generated access key.
   */
  accessKey: string;
  /**
   * Founder allocation number from 1 to 50.
   */
  founderNumber?: number | null;
  /**
   * Founder Key assigned to this customer.
   */
  founderKey?: (number | null) | FounderKey;
  /**
   * Date and time when Founder Key was issued.
   */
  keyIssuedAt?: string | null;
  /**
   * Current state of the access request.
   */
  status?: ('PENDING' | 'SENT' | 'USED' | 'REJECTED') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "founder-keys".
 */
export interface FounderKey {
  id: number;
  key: string;
  status?: ('AVAILABLE' | 'ASSIGNED' | 'USED' | 'EXPIRED') | null;
  assignedTo?: (number | null) | User;
  batch: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist".
 */
export interface Waitlist {
  id: number;
  fullName: string;
  email: string;
  phoneNumber?: string | null;
  birthDate?: string | null;
  /**
   * Access key generated for this customer.
   */
  accessKey?: string | null;
  /**
   * Current waitlist status.
   */
  status?: ('PENDING' | 'SHORTLISTED' | 'KEY_ISSUED') | null;
  /**
   * Founder Key assigned to this waitlist customer.
   */
  founderKey?: (number | null) | FounderKey;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  shippingAddress: {
    street: string;
    city: string;
  };
  user?: (number | null) | User;
  items: {
    product: number | Product;
    quantity: number;
    unitPrice: number;
    size?: string | null;
    id?: string | null;
  }[];
  subtotal: number;
  discount?: number | null;
  /**
   * Customer pays shipping to maintain premium perception
   */
  shippingFee: number;
  totalAmount: number;
  isFounderOrder?: boolean | null;
  paymentStatus?: ('PENDING' | 'PAID' | 'FAILED') | null;
  orderStatus?: ('PROCESSING' | 'SHIPPED' | 'DELIVERED' | 'CANCELLED') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  msrp: number;
  founderPrice: number;
  gsm?: number | null;
  fabric?: string | null;
  printType?: string | null;
  category: number | Category;
  status?: ('DRAFT' | 'AVAILABLE' | 'SOLD_OUT') | null;
  images: {
    image: number | Media;
    id?: string | null;
  }[];
  totalStock: number;
  reservedStock?: number | null;
  soldStock?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  heroImage?: (number | null) | Media;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  /**
   * Customer Email or ID from frontend
   */
  customer: string;
  /**
   * Product ID or SKU
   */
  product: string;
  type: 'TEXT' | 'PHOTO' | 'VIDEO';
  content: string;
  status?: ('PENDING' | 'APPROVED' | 'REJECTED') | null;
  /**
   * Uploaded Media IDs array
   */
  media?:
    | {
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  discountCode?: string | null;
  discountPercentage?: number | null;
  /**
   * Track if n8n pushed this UGC video to Meta/TikTok Ads
   */
  pushedToAds?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "founder-profiles".
 */
export interface FounderProfile {
  id: number;
  user: number | User;
  founderNumber: number;
  physicalKeySerial?: string | null;
  joinedAt?: string | null;
  lifetimeDiscount?: number | null;
  annualSpend?: number | null;
  annualSpendCap?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'access-requests';
        value: number | AccessRequest;
      } | null)
    | ({
        relationTo: 'waitlist';
        value: number | Waitlist;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'founder-profiles';
        value: number | FounderProfile;
      } | null)
    | ({
        relationTo: 'founder-keys';
        value: number | FounderKey;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phoneNumber?: T;
  role?: T;
  birthDate?: T;
  isFounder?: T;
  founderNumber?: T;
  annualSpend?: T;
  referralCode?: T;
  originPoints?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-requests_select".
 */
export interface AccessRequestsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phoneNumber?: T;
  birthDate?: T;
  accessKey?: T;
  founderNumber?: T;
  founderKey?: T;
  keyIssuedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist_select".
 */
export interface WaitlistSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phoneNumber?: T;
  birthDate?: T;
  accessKey?: T;
  status?: T;
  founderKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  shippingAddress?:
    | T
    | {
        street?: T;
        city?: T;
      };
  user?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        unitPrice?: T;
        size?: T;
        id?: T;
      };
  subtotal?: T;
  discount?: T;
  shippingFee?: T;
  totalAmount?: T;
  isFounderOrder?: T;
  paymentStatus?: T;
  orderStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  customer?: T;
  product?: T;
  type?: T;
  content?: T;
  status?: T;
  media?:
    | T
    | {
        file?: T;
        id?: T;
      };
  discountCode?: T;
  discountPercentage?: T;
  pushedToAds?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  heroImage?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  msrp?: T;
  founderPrice?: T;
  gsm?: T;
  fabric?: T;
  printType?: T;
  category?: T;
  status?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  totalStock?: T;
  reservedStock?: T;
  soldStock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "founder-profiles_select".
 */
export interface FounderProfilesSelect<T extends boolean = true> {
  user?: T;
  founderNumber?: T;
  physicalKeySerial?: T;
  joinedAt?: T;
  lifetimeDiscount?: T;
  annualSpend?: T;
  annualSpendCap?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "founder-keys_select".
 */
export interface FounderKeysSelect<T extends boolean = true> {
  key?: T;
  status?: T;
  assignedTo?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batch-001-settings".
 */
export interface Batch001Setting {
  id: number;
  founderCap: number;
  currentFounderCount: number;
  batchStatus?: ('LOCKED' | 'FOUNDER_ACCESS' | 'PUBLIC_RELEASE') | null;
  founderDiscountPercentage: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batch-001-settings_select".
 */
export interface Batch001SettingsSelect<T extends boolean = true> {
  founderCap?: T;
  currentFounderCount?: T;
  batchStatus?: T;
  founderDiscountPercentage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}